import store from '@/store';

import WSStore from '@/env/insyde/store/modules/WSStore';
import MenuStore from '@/env/insyde/store/modules/MenuStore';
import Networks from '@/env/insyde/store/modules/Networks';
// import BiosStore from '@/env/insyde/store/modules/Bios/BiosStore';
import BiosCGIStore from '@/env/insyde/store/modules/Bios/BiosCGIStore';
import SysinfoStore from '@/env/insyde/store/modules/SysinfoStore';
import PfrinfoStore from '@/env/insyde/store/modules/Pfrinfo/PfrinfoStore';
import FruStore from '@/env/insyde/store/modules/Fru/FruStore';
import SensorReadingsStore from '@/env/insyde/store/modules/SensorReadings/SensorReadingsStore';
import ADStore from '@/env/insyde/store/modules/AD/ADStore';
import VLANStore from '@/env/insyde/store/modules/VLAN/VLANStore';
import SELStore from '@/env/insyde/store/modules/SEL/SELStore';
import CertStore from '@/env/insyde/store/modules/CERT/CertStore';
import RADIUStore from '@/env/insyde/store/modules/RADIUS/RADIUStore';
import SecuritySettingsStore from '@/env/insyde/store/modules/SecuritySettings/SecuritySettingsStore';
import KRBAuthStore from '@/env/insyde/store/modules/krbAuth/KrbAuthStore';
import DDNSStore from '@/env/insyde/store/modules/DDNS/DDNSStore';
import CpuStore from '@/env/insyde/store/modules/Cpu/CpuStore';
import PcieStore from '@/env/insyde/store/modules/Pcie/PcieStore';
import BootSettingsStore from '@/env/insyde/store/modules/BootSettingsStore';
import SolLogStore from '@/env/insyde/store/modules/SolLogStore';
import BiosLogStore from '@/env/insyde/store/modules/BiosLogStore';
import PldFirmwareStore from '@/env/insyde/store/modules/PldFirmwareStore';
import AmdFirmwareStore from '@/env/insyde/store/modules/AmdFirmwareStore';
import HeartBeatStore from '@/env/insyde/store/modules/HeartBeatStore';
import CurrentUsersStore from '@/env/insyde/store/modules/CurrentUsersStore';
import NvmeStore from '@/env/insyde/store/modules/NvmeStore';
import SyslogStore from '@/env/insyde/store/modules/Syslog/SyslogStore';
import PowerCappingStore from '@/env/insyde/store/modules/PowerCapping/PowerCappingStore';
import AlertsStore from '@/env/insyde/store/modules/Alerts/AlertsStore';
import AlertPoliciesStore from '@/env/insyde/store/modules/AlertPolicies/AlertPoliciesStore';
import VFPStore from '@/env/insyde/store/modules/VirtualFrontPanel/VFPStore';
import AlertEmailStore from '@/env/insyde/store/modules/AlertEmail/AlertEmailStore';
import BackupRestoreStore from '@/env/insyde/store/modules/BackupRestore/BackupRestoreStore';
import InsydeMemoryStore from '@/env/insyde/store/modules/MemoryStore';
import UsersStore from '@/env/insyde/store/modules/UsersStore';
import Ipv4AccessControlStore from '@/env/insyde/store/modules/Ipv4AccessControlStore';
import Ipv6AccessControlStore from '@/env/insyde/store/modules/Ipv6AccessControlStore';
import PowerTelemetryStore from '@/env/insyde/store/modules/PowerTelemetryStore';
import PowerStatisticsStore from '@/env/insyde/store/modules/PowerStatisticsStore';
import InsydeFactoryResetStore from '@/env/insyde/store/modules/FactoryResetStore';
import UnitResetStore from '@/env/insyde/store/modules/UnitResetStore';
import DateTimeStore from '@/env/insyde/store/modules/DateTimeStore';
import DashboardStore from '@/env/insyde/store/modules/Dashboard/DashboardStore';
import LdapStore from '@/env/insyde/store/modules/LdapStore';
import SystemDiagnosticsStore from '@/env/insyde/store/modules/SystemDiagnosticsStore';
import TACACSStore from '@/env/insyde/store/modules/TACACS/TacacsStore';
import ConfigSolSmashStore from '@/env/insyde/store/modules/ConfigSolSmashStore';
import PowerScheduleStore from '@/env/insyde/store/modules/PowerScheduleStore';
import PostCodeStore from '@/env/insyde/store/modules/PostCodeStore';
import VideoLogStore from '@/env/insyde/store/modules/VideoLogStore';
import MemoryFPStore from '@/env/insyde/store/modules/MemoryFPStore';
import NicInformationStore from '@/env/insyde/store/modules/NicInformationStore';

store.registerModule('ws', WSStore);
store.registerModule('menu', MenuStore);
// store.registerModule('bios', BiosStore);
store.registerModule('bios', BiosCGIStore);
store.registerModule('sysinfo', SysinfoStore);
store.registerModule('fru', FruStore);
store.registerModule('pfrinfo', PfrinfoStore);
store.registerModule('sensoreadings', SensorReadingsStore);
store.registerModule('ad', ADStore);
store.registerModule('vlan', VLANStore);
store.registerModule('sel', SELStore);
store.registerModule('cert', CertStore);
store.registerModule('ddns', DDNSStore);
store.registerModule('radius', RADIUStore);
store.registerModule('securitysettings', SecuritySettingsStore);
store.registerModule('krbauth', KRBAuthStore);
store.registerModule('cpu', CpuStore);
store.registerModule('networks', Networks);
store.registerModule('syslog', SyslogStore);
store.registerModule('powercapping', PowerCappingStore);
store.registerModule('pcie', PcieStore);
store.registerModule('bootConfig', BootSettingsStore);
store.registerModule('solLog', SolLogStore);
store.registerModule('biosLog', BiosLogStore);
// PLD Firmware
store.registerModule(['firmware', 'pld'], PldFirmwareStore);
// AMD Firmware
store.registerModule(['firmware', 'amd'], AmdFirmwareStore);
// HeartBeat
store.registerModule('insydememorystore', InsydeMemoryStore);
store.registerModule(['heartbeat'], HeartBeatStore);
store.registerModule('nvmestore', NvmeStore);
store.registerModule('alerts', AlertsStore);
store.registerModule('alertpolicies', AlertPoliciesStore);
store.registerModule('vfp', VFPStore);
store.registerModule('tacacs', TACACSStore);
store.registerModule('alertemail', AlertEmailStore);
store.registerModule('backuprestore', BackupRestoreStore);
store.registerModule(['currentUsers'], CurrentUsersStore);
store.registerModule(['users'], UsersStore);
store.registerModule(['ipv4AccessControl'], Ipv4AccessControlStore);
store.registerModule(['ipv6AccessControl'], Ipv6AccessControlStore);
store.registerModule(['powerTelemetryStore'], PowerTelemetryStore);
store.registerModule(['powerStatisticsStore'], PowerStatisticsStore);
store.registerModule('insydeFactoryReset', InsydeFactoryResetStore);
store.registerModule(['unitReset'], UnitResetStore);
store.registerModule(['datetimestore'], DateTimeStore);
store.registerModule(['dashboardstore'], DashboardStore);
store.registerModule('ldapinsyde', LdapStore);
store.registerModule('diagnostics', SystemDiagnosticsStore);
store.registerModule('configSolSmash', ConfigSolSmashStore);
store.registerModule('powerSchedule', PowerScheduleStore);
store.registerModule('postCode', PostCodeStore);
store.registerModule('videoLog', VideoLogStore);
store.registerModule('memoryFP', MemoryFPStore);
store.registerModule('nicInformation', NicInformationStore);

export default store;
